### ISSUE TITLE
503 Server Unavailable issue (mostly on windows)

### ISSUE THREAD

**Issue by pi0** [nitrojs/nitro#1454]
Related: 
- https://github.com/unjs/nitro/issues/1338
- https://github.com/unjs/nitro/issues/310
- https://github.com/unjs/nitro/issues/305
- https://github.com/nuxt/nuxt/issues/15188
- https://github.com/nuxt/nuxt/issues/22150

Fix attempts:
- https://github.com/unjs/nitro/pull/1115

This issue has been mentioned by several users (mostly on Windows) that the dev server socket might go unavailable with 503 when having concurrency. 

Right now there is no solid minimal reproduction with Nitro alone in order to isolate and resolve the root cause of the issue but it is certainly a valid issue that has been reported several times and needs to be resolved.

**Comment by mrniamster** [comment]
@pi0  Pooya -  just to update, i'm using mac and windows both, getting this on both of them

**Comment by pi0** [comment]
Related: I am planning to replace old [http-proxy](https://github.com/http-party/node-http-proxy) used in [dev server](https://github.com/unjs/nitro/blob/1b9f51b7955d2490b1fd8da73af40780f30a1235/src/dev/server.ts#L257) with a better implementation. I will try to reproduce the issue with old package anyway but at the moment i think it is the most likely source of the issues.

**Comment by mrniamster** [comment]
@pi0  if you need, i can share my codebase to reproduce this error,
here is my email, niteshkmr366@gmail.com

**Comment by vaheqelyan** [comment]
Same for me on linux, using `Nuxt 3.8.0 with Nitro 2.7.0`

**Comment by svekke** [comment]
Any update on this?

**Comment by carbdias** [comment]
Hello, is there any news on this?
For me it is very wierd that a get call directly in the browser works, and then with useFetch inside a plugin, it returns this error.
I've already try not using useFetch but only $fetch in the plugin (in case this composable didn't work here), but the error is the same

it seems something is blocking the http call or returning a bad response (503)

**Comment by Abernethy-BY** [comment]
I encountered the same problem, is there any solution? thanks
​

**Comment by carbdias** [comment]
I've also had a probñem there. I had to redo the project from scratch with the devtools always on, to be sure it didn't crash anytime.

**Comment by Abernethy-BY** [comment]
> I encountered the same problem, is there any solution? thanks​
> 
> The server seems to be working normally in my case, but there is a problem with the display of devtool

It should be added that this problem currently only occurs in the Windows development environment, and does not have this problem in the Linux server environment.

**Comment by cmcnicholas** [comment]
Surprised there isn't bigger noise around this issue, I encounter this every day working on a smallish nuxt app

**Comment by tbarus** [comment]
same issue I am having

**Comment by lucas-santosP** [comment]
Im facing this problem too using Nuxt, and as a workaround I could solve it using `yarn dev --host` and accessing the website using the network address.

The problem only occurs to me when using a specific public WIFI network with my company's computer which has firewall configurations. So I have my suspicions that this issue has something to do with security and permissions.

**Comment by carbdias** [comment]
I have here the same issue in this reproduction
it is a most recently created project, with little code, but it is taking forever loading the page, and before it was giving 503 error, then I installed npm@latest globally, and not it is just taking forever and not leading. I just checked, 503 fetching loclahost.
https://stackblitz.com/edit/github-4zdfkx?file=package.json

**Comment by carbdias** [comment]
for me this was solved with npm cache verify and opening the app in incognito mode. 
somehow nuxt framework is generating too much temp files or files in cache (I asume the idea was to improve performance) but it is blocking things.
somehow older and larger applications I had didn't present this problem.
just fresh started projects.

**Comment by dan-hammond** [comment]
I just wanted to add that we're still experiencing this a lot in our Nuxt 3 site which proxies a few routes to an old SPA (which is quite heavy with lots of requests). On Windows, some of the proxied requests will fail with an error 503. It's completely random as to which ones. I don't experience it while developing the same site on my Mac. It is definitely related to there being lots of concurrent requests though - it doesn't do it if there's only a few at once.
 
The workarounds listed above of trying via different network addresses don't seem to help. If we switch to an alternative proxy solution, such as nginx in a Docker container, that works fine. We'd prefer to use Nuxt as our proxy while developing though, as it's quicker and easier, with fewer dependencies.

**Comment by kdydesign** [comment]
Is there any temporary way to address this issue?

**Comment by poziminski** [comment]
We are facing this issue since we started new project with Nuxt 3. It works fine on production build, but we cannot develop. Happens on Macbook in Docker containers.
Refer to my comment here: https://github.com/nuxt/nuxt/issues/23832#issuecomment-2494468441

Here's a reproduction code: https://github.com/poziminski/nuxt-bug-reproduction

**Comment by kabforks** [comment]
I recently upgraded vinxi to 0.50, I have this issue as well. From what I can tell, every request that comes from `throw createError `will result in a 503 error. The response in the browser is `content type` with `text/html` and the content is 

```
        <header>
          <h2>503 Server Unavailable</h2>
        </header>
        <code><pre>Error: Not found 
    at createError (file:///C:/src/temp/yes/node_modules/.pnpm/h3@1.13.0/node_modules/h3/dist/index.mjs:78:15)
    at eval (C:/src/temp/yes/packages/test/src/api/index.ts:80:52)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async _callHandler (file:///C:/src/temp/yes/node_modules/.pnpm/h3@1.13.0/node_modules/h3/dist/index.mjs:1837:16)
    at async Object.handler (file:///C:/src/temp/yes/node_modules/.pnpm/h3@1.13.0/node_modules/h3/dist/index.mjs:1978:19)
    at async Server.toNodeHandle (file:///C:/src/temp/yes/node_modules/.pnpm/h3@1.13.0/node_modules/h3/dist/index.mjs:2270:7)
    </pre></code>
```

It doesn't matter what I put in `createError()` -- it all returns 503. My solution for now is to simply return an object, and not use createError.
